### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by profesionalleet1337** [mishakorzik/Mask-Phish#2]
Here is the MaskPhish URL: https://www.xxx.bg/com - @Error: Sorry, the URL you entered is on our internal blacklist. It may have been used abusively in the past, or it may link to another URL redirection service. 

Doesn't work with any site, I enter ? The link which I generate are from cloudflare/ loxalxpose?

**Comment by mishakorzik** [comment]
Use: https://github.com/mishakorzik/mask-url
